aliases:
  - &containerize_push
    name: Containerize and Push
    command: |
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker build -t --build-arg SW_HOSTNAME=$HOSTNAME aeternas/swadeshness-couperose-master . && \
      docker push aeternas/swadeshness-couperose-master

version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
        
      - run: lein test
      - run: lein uberjar 
      - store_artifacts:
          path: target/uberjar/couperose-0.1.0-SNAPSHOT-standalone.jar
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy: *containerize_push
