aliases:
  - &git_checkout
    name: Checkout
    command: |
      mkdir -p ~/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config && \
      git clone --depth 1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git reset --hard $CIRCLE_SHA1
  - &environment
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
  - &install_dependencies
    name: Install Dependencies
    command: lein deps
  - &run_tests
    name: Run Unit Tests
    command: lein test
  - &make_executable
    name: Make Jar Executable
    command: lein uberjar
  - &export_envs
    name: Export ENVs
    command: |
      if [ $CIRCLE_BRANCH == "master" ]; then 
        echo 'export HOSTNAME="$PROD_HOSTNAME"' >> $BASH_ENV
      else 
        echo 'export HOSTNAME="$DEV_HOSTNAME"' >> $BASH_ENV 
      fi
  - &update_submodules
    name: Update submodules
    command: |
      git submodule init && \
      git submodule update
  - &setup_remote_docker
    setup_remote_docker:
      docker_layer_caching: false
  - &containerize_push
    name: Containerize and Push
    command: |
      echo $DOCKER_PASSWORD > docker_passwd && \
      docker login -u $DOCKER_USERNAME --password-stdin < docker_passwd && rm docker_passwd && \
      docker build --build-arg SW_HOSTNAME=$HOSTNAME -t aeternas/swadeshness-couperose:$CIRCLE_BRANCH . && \
      docker push aeternas/swadeshness-couperose:$CIRCLE_BRANCH
      if [[ $CIRCLE_BRANCH == "master" ]]; then \
        docker tag aeternas/swadeshness-couperose:master aeternas/swadeshness-couperose:latest && \
        docker push aeternas/swadeshness-couperose:latest
      fi
  - &restore_cache
    keys:
      - v1-dependencies-{{ checksum "project.clj" }}
      - v1-dependencies-
  - &save_cache
    paths:
      - ~/.m2
    key: v1-dependencies-{{ checksum "project.clj" }}
  - &run_warm_cache
    name: Warm Cache
    command: |
      java -jar couperose-0.1.0-SNAPSHOT-standalone.jar
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.3
    working_directory: ~/repo
    environment: *environment
    steps:
      - run: *git_checkout
      - run: *update_submodules
      - restore_cache: *restore_cache
      - run: *install_dependencies
      - save_cache: *save_cache
      - run: *run_tests
      - run: *make_executable 
      - run: *export_envs
      - *setup_remote_docker
      - deploy: *containerize_push
  run:
    docker:
      - image: aeternas/swadeshness-couperose:$CIRCLE_BRANCH
    working_directory: /home/circleci/repo
    steps:
      - deploy: *run_warm_cache
# -------------------------
#        WORK FLOWS
# -------------------------
workflows:
  version: 2.1
  build-run:
    jobs:
      - build
      - run:
          requires:
            - build
